/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrowseIndexRouteImport } from './routes/browse/index'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as GameIdProtectedRouteImport } from './routes/$gameId/_protected'
import { Route as GameIdProtectedMatchIdIndexRouteImport } from './routes/$gameId/_protected/$matchId/index'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseIndexRoute = BrowseIndexRouteImport.update({
  id: '/browse/',
  path: '/browse/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const GameIdProtectedRoute = GameIdProtectedRouteImport.update({
  id: '/$gameId/_protected',
  path: '/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const GameIdProtectedMatchIdIndexRoute =
  GameIdProtectedMatchIdIndexRouteImport.update({
    id: '/$matchId/',
    path: '/$matchId/',
    getParentRoute: () => GameIdProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$gameId': typeof GameIdProtectedRouteWithChildren
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/browse/': typeof BrowseIndexRoute
  '/$gameId/$matchId/': typeof GameIdProtectedMatchIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$gameId': typeof GameIdProtectedRouteWithChildren
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/browse': typeof BrowseIndexRoute
  '/$gameId/$matchId': typeof GameIdProtectedMatchIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_public': typeof PublicRouteWithChildren
  '/$gameId/_protected': typeof GameIdProtectedRouteWithChildren
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/browse/': typeof BrowseIndexRoute
  '/$gameId/_protected/$matchId/': typeof GameIdProtectedMatchIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$gameId'
    | '/login'
    | '/register'
    | '/browse/'
    | '/$gameId/$matchId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$gameId'
    | '/login'
    | '/register'
    | '/browse'
    | '/$gameId/$matchId'
  id:
    | '__root__'
    | '/'
    | '/_public'
    | '/$gameId/_protected'
    | '/_public/login'
    | '/_public/register'
    | '/browse/'
    | '/$gameId/_protected/$matchId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PublicRoute: typeof PublicRouteWithChildren
  GameIdProtectedRoute: typeof GameIdProtectedRouteWithChildren
  BrowseIndexRoute: typeof BrowseIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/': {
      id: '/browse/'
      path: '/browse'
      fullPath: '/browse/'
      preLoaderRoute: typeof BrowseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/$gameId/_protected': {
      id: '/$gameId/_protected'
      path: '/$gameId'
      fullPath: '/$gameId'
      preLoaderRoute: typeof GameIdProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$gameId/_protected/$matchId/': {
      id: '/$gameId/_protected/$matchId/'
      path: '/$matchId'
      fullPath: '/$gameId/$matchId/'
      preLoaderRoute: typeof GameIdProtectedMatchIdIndexRouteImport
      parentRoute: typeof GameIdProtectedRoute
    }
  }
}

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface GameIdProtectedRouteChildren {
  GameIdProtectedMatchIdIndexRoute: typeof GameIdProtectedMatchIdIndexRoute
}

const GameIdProtectedRouteChildren: GameIdProtectedRouteChildren = {
  GameIdProtectedMatchIdIndexRoute: GameIdProtectedMatchIdIndexRoute,
}

const GameIdProtectedRouteWithChildren = GameIdProtectedRoute._addFileChildren(
  GameIdProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PublicRoute: PublicRouteWithChildren,
  GameIdProtectedRoute: GameIdProtectedRouteWithChildren,
  BrowseIndexRoute: BrowseIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
