services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command:
      - redis-server
      - --requirepass
      - "6767"
      - --appendonly
      - yes
    networks:
      - redis-network

  insights:
    image: redis/redisinsight:latest
    container_name: redis-insight
    restart: unless-stopped
    ports:
      - "5540:5540"
    volumes:
      - redisinsight-data:/data
    networks:
      - redis-network
    depends_on:
      - redis

volumes:
  redis-data:
  redisinsight-data:

networks:
  redis-network:
    driver: bridge
